apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: ClusterIP
  selector:
    app: app-pod
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      terminationGracePeriodSeconds: 20 # https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace
      # used for close processes in the app and stop receiving traffic
      containers:
        - name: app
          image: app:1.1.0
          ports:
            - containerPort: 5000
              name: http
          livenessProbe:
            httpGet:
              port: 5000
              path: "/health/liveness"
          readinessProbe:
            httpGet:
              port: 5000
              path: "/health/readiness"
          startupProbe:
            httpGet:
              port: 5000
              path: "/health/startup"
            initialDelaySeconds: 30
            failureThreshold: 6