apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  containers:
    - name: toolbox
      image: pnowy/toolbox:1.0.0
      command: [ 'sh', '-c', 'echo "HELLO probe test!" && sleep infinity' ] # for unhealthy status
      #command: [ 'sh', '-c', 'echo "HELLO probe test!" && touch /tmp/healthy && sleep infinity' ] # for healthy status
      livenessProbe:
        initialDelaySeconds: 3
        periodSeconds: 5
        exec:
          command:
            - cat
            - /tmp/healthy
      resources:
        limits:
          cpu: "200m"
          memory: "32Mi"