apiVersion: rbac.authorization.k8s.io/v1
kind: Role # | ClusterRole for all nodes
metadata:
  name: pod-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # | ClusterRoleBinding for all nodes
metadata:
  name: read-pods
subjects:
  - kind: ServiceAccount
    name: test-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader