apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: test-sa-secret
  annotations:
    kubernetes.io/service-account.name: test-sa
type: kubernetes.io/service-account-token

# kubectl get secret test-sa-secret -o jsonpath='{.data.token}' | base64 --decode