apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  LOGGING_LEVEL: "ERROR"
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: ClusterIP
  selector:
    app: app-pod
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      containers:
        - name: app
          image: app:1.0.0
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: LOGGING_LEVEL_APP
              valueFrom:
                configMapKeyRef:
                  key: LOGGING_LEVEL
                  name: app-config
            - name: PASSWORD_APP
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: app-secrets
          envFrom:
            # use ConfigMap
            - configMapRef:
                name: app-config
            # use Secret
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
data:
  USERNAME: YWRtaW4K # data needs to be encoded base64
stringData:
  PASSWORD: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-secret
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: admin