apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    tier: frontend
    team: blue
  annotations:
    myapp.io/version.commit: "dko2mdiska9"
    myapp.io/checksum: "2020bbbee3030cee20320cccc202kdksas00000022m2k3m3"
spec:
  containers:
    - name: nginx
      image: nginx:1.23.4
---
apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    tier: backend
    function: rest-api
    technology: python-flask
    team: green
spec:
  containers:
    - name: app
      image: app:1.0.0
---
apiVersion: v1
kind: Pod
metadata:
  name: app2
  labels:
    tier: backend
    team: yellow
spec:
  containers:
    - name: app
      image: app:1.0.0