apiVersion: batch/v1
kind: Job
metadata:
  name: probability-job
spec:
  backoffLimit: 12 # Number of retries before marking this job failed. Default is 6
  completions: 4 # Desired number of successfully finished pods the job should be run with. Default is 1
  #parallelism: 3 # Maximum desired number of pods the job should run at any given time
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: toolbox
          image: pnowy/toolbox:1.0.0
          command:
            - "/bin/bash"
            - "-c"
            - |
              #!/bin/bash
              # Function to generate a random number between 1 and 100
              random_number() {
                echo $((RANDOM % 100 + 1))
              }
              # Function to generate an error with a given probability
              generate_random_error() {
                local probability=$1
                local rand=$(random_number)
                if [ "$rand" -le "$probability" ]; then
                  echo "Error!"
                  exit 1 # Exit with error code 1
                else
                  echo "Success!"
                  exit 0 # Exit with success code 0
                fi
              }
              # Set the desired probability of error (change this value to your desired percentage)
              probability_of_error=50 # probability of error
              generate_random_error $probability_of_error