apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  accessModes:
    - ReadWriteOnce # ReadOnlyMany / ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain # Delete
  storageClassName: "host-path"
  hostPath:
    path: /data/pv01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "host-path"
  volumeName: pv01
---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  terminationGracePeriodSeconds: 0
  volumes: # PersistentVolumeClaim
    - name: data
      persistentVolumeClaim:
        claimName: pvc01
  containers:
    - name: toolbox
      image: pnowy/toolbox:1.0.0
      workingDir: "/app"
      command: [ "sh", "-c" ]
      args:
        - mkdir -p /app && echo "Work done $HOSTNAME $(date +%Y-%m-%d_%H-%M-%S)" >> /app/data.txt && sleep infinity
      volumeMounts: # PersistentVolume
        - mountPath: /app
          name: data