apiVersion: v1
kind: Service
metadata:
  name: app # it will be used as DNS name
spec:
  type: ClusterIP # default type
  selector: # related to Pods, not Deployment!
    app: app-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http # or can be used container port, in this case is 5000. Follow pod specification.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      containers:
        - name: app
          image: app:1.0.0
          ports:
            - containerPort: 5000
              name: http
---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  containers:
    - name: toolbox
      image: pnowy/toolbox:1.0.0
      command: [ 'sh', '-c', 'echo "Hello, Kubernetes!" && sleep infinity' ]